//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class employee
    {
        public int id { get; set; }

        [DisplayName("Employee Name")]
        [Required(ErrorMessage ="Name is required")]
        public string name { get; set; }

            
        [DisplayName("Employee Designation")]
        [Required (ErrorMessage ="Designation is required")]

        public string designation { get; set; }

        [DisplayName("Employee Image")]

        public string image_path { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }


    }
}
